config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :campaigns, only: [:index, :create, :new, :show, :destroy] do
    resource :search, only: [:new, :show]
    resources :permissions, only: [:create]
    resources :entries, only: [:index] do
      post 'submit', on: :collection
    end
    resources :duplicates, only: [:index, :show] do
      post 'merge', on: :member
      post 'reject', on: :member
    end
    get 'export', on: :member
  end
  resources :entries, only: [:show, :update, :edit]
  resources :visits, only: [:edit, :update]

  root to: "home#show"

  get 'hello_world', to: 'hello_world#index'
end

app/models/entry.rb
class Entry < ApplicationRecord
	AGE_GROUPS = {
		"1" => "Children",
		"2" => "Junior Youth",
		"3" => "Youth"
	}

	belongs_to :campaign
	has_many :duplicates, foreign_key: :entry1_id, dependent: :destroy
	has_many :more_duplicates, class_name: "Duplicate", foreign_key: :entry2_id, dependent: :destroy
	has_many :visits, -> { order(date: :desc, created_at: :desc) }, dependent: :destroy
	validates :street, presence: true
	validates :street_number, presence: true
	validates :last_outcome, presence: true, inclusion: { in: Visit::OUTCOMES.keys }
	validates :last_visit, presence: :true
	validate :validate_age_groups

	before_save :uniq_arrays

	def validate_age_groups
		if !age_groups.is_a?(Array) || age_groups.detect{|a| !AGE_GROUPS.keys.include?(a)}
			errors.add(:age_groups, :invalid)
		end
	end

	def uniq_arrays
		self.age_groups.uniq!
	end

	def full_address
		"#{street_number} #{street}" + (unit_number.blank? ? "" : " ##{unit_number}")
	end

	def last_outcome_text
		Visit::OUTCOMES[last_outcome]
	end

	def all_themes
		visits.flat_map{|v| v.themes}.uniq.sort
	end

	def all_notes
		visits.map{|v| v.notes}.select(&:present?).join("\n\n")
	end

	def all_teams
		visits.map{|v| v.team}.select(&:present?).uniq.join("; ")
	end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_action :require_login, except: [:index, :submit]
	skip_before_action :verify_authenticity_token, only: [:submit]

	def show
		@entry = Entry.find(params[:id])
		@visits = @entry.visits.to_a
		@campaign = @entry.campaign
		unless current_user.can_see?(@campaign)
			redirect_to '/'
			return
		end
	end

	def index
		begin
			@campaign = Campaign.find(entry_params[:campaign_id])
		rescue ActiveRecord::RecordNotFound
			redirect_to '/'
		end
	end

	def submit
		successes = {}
		submitparams = params.permit(:entries, :campaign_id)
		params[:entries].each do |record|
			entry = Entry.new(submit_entry_params(record))
			entry.campaign_id = params[:campaign_id]
			entry.user_email = current_user.email if current_user

			visit = Visit.new(submit_visit_params(record))
			entry[:last_outcome] = visit.outcome
			entry[:last_visit] = visit.date

			Entry.transaction do
				if entry.save
					entry.visits << visit
					visit.save
					successes[record[:timestamp]] = true
				end
			end
		end
		render json: {successes: successes}
	end

	def edit
		@entry = Entry.find(params[:id])
		@visits = @entry.visits
		@campaign = @entry.campaign
		unless current_user.can_see?(@campaign)
			redirect_to '/'
			return
		end
	end

	def update
		@entry = Entry.find(params[:id])
		unless current_user.can_see?(@entry.campaign)
			redirect_to '/'
			return
		end

		@entry.update!(entry_params)
		redirect_to action: :show, id: params[:id]
	end

	def destroy
	end

	def submit_entry_params(entry)
		entry.require(:entry).permit(
			:street,
			:street_number,
			:unit_number,
			:people,
			:contact,
			:age_groups => [],
		)
	end

	def submit_visit_params(entry)
		entry.require(:entry).permit(
			:team,
			:date,
			:time,
			:outcome,
			:notes,
			:themes => [],
		)
	end

	def entry_params
		params.permit(
			:campaign_id,
			:team,
			:date,
			:time,
			:street,
			:street_number,
			:unit_number,
			:last_outcome,
			:people,
			:contact,
			:notes,
			:age_groups => [],
			:themes => []
		)
	end
end

app/views/entries/edit.html.erb
<h3 class="card-title"><%= @campaign.name %></h3>
<%= form_tag(entry_path(@entry.id), method: "PUT") do %>
	<div class="form-group">
		<label for="street">Street:</label>
		<input type="text" class="form-control" name="street" id="street" placeholder="Street" autocomplete="off" value="<%= @entry.street %>" />
	</div>
	<div class="row">
		<div class="form-group col">
			<label for="street-number">Street Number:</label>
			<input type="text" class="form-control" name="street_number" id="street-number" placeholder="Street Number" autocomplete="off" value="<%= @entry.street_number %>" />
		</div>
		<div class="form-group col">
			<label for="unit">Apartment/Unit:</label>
			<input type="text" class="form-control" name="unit_number" id="unit" placeholder="Apartment/Unit" autocomplete="off" value="<%= @entry.unit_number %>" />
		</div>
	</div>
	<div class="form-group">
		<label for="people">Residents:</label>
		<input type="text" class="form-control" name="people" id="people" placeholder="Names/Ages/Relationships of Residents" autocomplete="off" value="<%= @entry.people %>" />
	</div>
	<div class="form-group">
		<label for="contact">Contact Information:</label>
		<input type="text" class="form-control" name="contact" id="contact" placeholder="Phone/Email" autocomplete="off" value="<%= @entry.contact %>" />
	</div>
	<div class="form-group row">
		<div class="col col-auto">Age Groups:</div>
		<div class="col">
			<% Entry::AGE_GROUPS.each do |id, group| %>
			<div class="form-check">
				<label class="form-check-label">
					<input type="checkbox" class="form-check-input age-groups" name="age_groups[]" value="<%= id %>" id="age-group-<%= id %>"<%= ' checked="checked"' if @entry.age_groups.include?(id) %> />
					<%= group %>
				</label>
			</div>
			<% end %>
		</div>
	</div>
	<div class="form-group">
		<label for="last-outcome">Last Outcome:</label>
		<select class="form-control" name="last_outcome" id="last-outcome">
			<% Visit::OUTCOMES.each do |id, outcome| %>
			<option value="<%= id %>"<%= ' selected="select"' if id == @entry.last_outcome %>><%= outcome %></option>
			<% end %>
		</select>
	</div>
	<div class="form-group">
		<button class="btn btn-primary right" type="submit">Update</button>
	</div>
<% end %>

app/views/entries/index.html.erb
<h3 class="card-title"><%= @campaign.name %></h3>
<form id="entries-form">
	<div class="row">
		<div class="form-group col-lg">
			<label for="team">Team Members:</label>
			<input type="text" class="form-control" name="team" id="team" placeholder="Team Members" autocomplete="off" />
		</div>
		<div class="form-group col-lg">
			<label for="date">Date:</label>
			<input type="date" class="form-control" name="date" id="date" value="" autocomplete="off" />
		</div>
	</div>
	<hr />
	<div class="form-group">
		<label for="street">Street:</label>
		<input type="text" class="form-control" name="street" id="street" placeholder="Street" autocomplete="off" />
	</div>
	<div class="row">
		<div class="form-group col">
			<label for="street-number">Street Number:</label>
			<input type="text" class="form-control" name="street_number" id="street-number" placeholder="Street Number" autocomplete="off" />
		</div>
		<div class="form-group col">
			<label for="unit">Apartment/Unit:</label>
			<input type="text" class="form-control" name="unit_number" id="unit" placeholder="Apartment/Unit" autocomplete="off" />
		</div>
	</div>
	<div class="form-group">
		<label for="outcome">Outcome:</label>
		<select class="form-control" name="outcome" id="outcome">
			<option value="">Please Select</option>
			<% Visit::OUTCOMES.each do |id, outcome| %>
			<option value="<%= id %>"><%= outcome %></option>
			<% end %>
		</select>
	</div>
	<div class="form-group">
		<label for="people">Residents:</label>
		<input type="text" class="form-control" name="people" id="people" placeholder="Names/Ages/Relationships of Residents" autocomplete="off" />
	</div>
	<div class="form-group">
		<label for="contact">Contact Information:</label>
		<input type="text" class="form-control" name="contact" id="contact" placeholder="Phone/Email" autocomplete="off" />
	</div>
	<div class="form-group row">
		<div class="col col-auto">Age Groups:</div>
		<div class="col">
			<% Entry::AGE_GROUPS.each do |id, group| %>
			<div class="form-check">
				<label class="form-check-label">
					<input type="checkbox" class="form-check-input age-groups" name="age_groups[]" value="<%= id %>" id="age-group-<%= id %>" />
					<%= group %>
				</label>
			</div>
			<% end %>
		</div>
	</div>
	<div class="form-group">
		Conversation Themes Covered:
		<% Visit::THEMES.each do |id, theme| %>
		<div class="form-check">
			<label class="form-check-label">
				<input type="checkbox" class="form-check-input themes" name="themes[]" value="<%= id %>" id="theme-<%= id %>" />
				<%= theme %>
			</label>
		</div>
		<% end %>
	</div>
	<div class="form-group">
		<label for="notes">Notes:</label>
		<textarea name="notes" id="notes" class="form-control" placeholder="Notes" rows="4"></textarea>
	</div>
	<div class="form-group">
		<button class="btn btn-primary right" type="button" id="entry-submit">Submit</button>
	</div>
</form>

app/views/entries/show.html.erb
<h3 class="card-title"><%= link_to "< "+ @campaign.name, campaign_path(@campaign.id) %></h3>
<dl>
	<dt>Address:</dt>
	<dd><%= @entry.full_address %></dd>

	<dt>Last Outcome:</dt>
	<dd><%= @entry.last_outcome_text %></dd>

	<dt>Residents:</dt>
	<dd><%= @entry.people.blank? ? "-" : @entry.people %></dd>

	<dt>Contact Information:</dt>
	<dd><%= @entry.contact.blank? ? "-" : @entry.contact %></dd>

	<dt>Age Groups:</dt>
	<dd><%= @entry.age_groups.empty? ? "-" : @entry.age_groups.map {|a| Entry::AGE_GROUPS[a]}.join(", ") %></dd>
</dl>
<%= link_to("Edit Entry", edit_entry_path(@entry.id), class: "btn btn-primary") %>

<% @visits.each_with_index do |visit, i| %>
<hr />
<h4><%= (@visits.size - i).ordinalize %> Visit &nbsp;&nbsp;<%= link_to "Edit Visit", edit_visit_path(visit.id), class: "btn btn-sm btn-primary" %></h4>
<dl>
	<dt>Team Members:</dt>
	<dd><%= visit.team %></dd>

	<dt>Date:</dt>
	<dd><%= visit.date %></dd>

	<dt>Outcome:</dt>
	<dd><%= visit.outcome_text %></dd>

	<dt>Conversation Themes Covered:</dt>
	<dd><%= visit.themes.empty? ? "-" : visit.themes.map {|a| Visit::THEMES[a]}.join(", ") %></dd>

	<dt>Notes:</dt>
	<dd><%=simple_format visit.notes.blank? ? "-" : visit.notes %></dd>
</dl>
<% end %>