config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :campaigns, only: [:index, :create, :new, :show, :destroy] do
    resource :search, only: [:new, :show]
    resources :permissions, only: [:create]
    resources :entries, only: [:index] do
      post 'submit', on: :collection
    end
    resources :duplicates, only: [:index, :show] do
      post 'merge', on: :member
      post 'reject', on: :member
    end
    get 'export', on: :member
  end
  resources :entries, only: [:show, :update, :edit]
  resources :visits, only: [:edit, :update]

  root to: "home#show"

  get 'hello_world', to: 'hello_world#index'
end

app/models/duplicate.rb
class Duplicate < ApplicationRecord
	belongs_to :campaign
	belongs_to :entry1, class_name: "Entry", foreign_key: "entry1_id"
	belongs_to :entry2, class_name: "Entry", foreign_key: "entry2_id"

	def self.create_for_entries(campaign_id, entry)
		ids = Entry.where(
			street_number: entry[:street_number],
			unit_number: entry[:unit_number],
			campaign_id: campaign_id)
			.order(id: :asc)
			.pluck(:id)
		ids.combination(2).each do |pair|
			Duplicate.where(
				campaign_id: campaign_id,
				entry1_id: pair.first,
				entry2_id: pair.last)
				.first_or_create(status: "potential")
		end
	end

	def visits
		@visits ||= (entry1.visits + entry2.visits).sort_by {|v| v.date}.reverse
	end

	def street
		entry1.street
	end

	def street_number
		entry1.street_number
	end

	def unit_number
		entry1.unit_number
	end

	def outcome
		if ["1", "2", "3"].include?(entry2.last_outcome)
			entry1.last_outcome
		else
			entry2.last_outcome
		end
	end

	def people
		@people ||= [entry1.people, entry2.people].select(&:present?).join("; ")
	end

	def contact
		@contact ||= [entry1.contact, entry2.contact].select(&:present?).join("; ")
	end

	def age_groups
		@age_groups ||= entry1.age_groups + entry2.age_groups
	end
end

app/controllers/duplicates_controller.rb
class DuplicatesController < ApplicationController
	before_action :require_login
	before_action :authz_check

	def index
		@duplicates = @campaign.duplicates.where(status: "potential").includes(:entry1, :entry2).to_a
		if @duplicates.empty?
			redirect_to campaign_path(@campaign.id)
		end
	end

	def show
		@duplicate = Duplicate.where(id: params[:id]).includes(:entry1, :entry2).take
	end

	def merge
		@duplicate = Duplicate.find(params[:id])
		Duplicate.transaction do
			@duplicate.entry2.visits.update_all(entry_id: @duplicate.entry1.id)
			@duplicate.entry1.update(duplicate_params.merge({
				last_visit: @duplicate.visits.first.date,
				last_outcome: @duplicate.outcome
			}))
			@duplicate.entry2.destroy
		end
		redirect_to action: :index, campaign_id: params[:campaign_id]
	end

	def reject
		@duplicate = Duplicate.find(params[:id])
		@duplicate.update(status: "rejected")
		redirect_to action: :index, campaign_id: params[:campaign_id]
	end

	private

	def campaign
		@campaign ||= Campaign.find(params[:campaign_id])
	end

	def authz_check
		unless current_user.can_see?(campaign)
			redirect_to '/'
		end
	end

	def duplicate_params
		params.permit(
			:street,
			:street_number,
			:unit_number,
			:people,
			:contact,
			:age_groups => [],
		)
	end
end

app/views/duplicates/index.html.erb
<h3 class="card-title"><%= @campaign.name %> Potential Duplicates</h3>

<table class="table">
	<thead>
		<tr>
			<th>First Address</th>
			<th>Second Address</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<% @duplicates.each do |duplicate| %>
		<tr>
			<td><%= duplicate.entry1.full_address %></td>
			<td><%= duplicate.entry2.full_address %></td>
			<td>
				<div class="row">
					<%= link_to "Merge", campaign_duplicate_path(@campaign.id, duplicate.id), class: "btn btn-primary" %>
					&nbsp;
					<%= form_tag(reject_campaign_duplicate_path(@campaign.id, duplicate.id), class: "form-inline") do %>
						<button type="submit" class="btn btn-danger">Reject</button>
					<% end %>
				</div>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/duplicates/show.html.erb
<h3 class="card-title">Merge Duplicates</h3>
<%= form_tag(merge_campaign_duplicate_path(@campaign.id, @duplicate.id)) do %>
	<div class="form-group">
		<label for="street">Street:</label>
		<input type="text" class="form-control" name="street" id="street" placeholder="Street" autocomplete="off" value="<%= @duplicate.street %>" />
	</div>
	<div class="row">
		<div class="form-group col">
			<label for="street-number">Street Number:</label>
			<input type="text" class="form-control" name="street_number" id="street-number" placeholder="Street Number" autocomplete="off" value="<%= @duplicate.street_number %>" />
		</div>
		<div class="form-group col">
			<label for="unit">Apartment/Unit:</label>
			<input type="text" class="form-control" name="unit_number" id="unit" placeholder="Apartment/Unit" autocomplete="off" value="<%= @duplicate.unit_number %>" />
		</div>
	</div>
	<div class="form-group">
		<label for="people">Residents:</label>
		<input type="text" class="form-control" name="people" id="people" placeholder="Names/Ages/Relationships of Residents" autocomplete="off" value="<%= @duplicate.people %>" />
	</div>
	<div class="form-group">
		<label for="contact">Contact Information:</label>
		<input type="text" class="form-control" name="contact" id="contact" placeholder="Phone/Email" autocomplete="off" value="<%= @duplicate.contact %>" />
	</div>
	<div class="form-group row">
		<div class="col col-auto">Age Groups:</div>
		<div class="col">
			<% Entry::AGE_GROUPS.each do |id, group| %>
			<div class="form-check">
				<label class="form-check-label">
					<input type="checkbox" class="form-check-input age-groups" name="age_groups[]" value="<%= id %>" id="age-group-<%= id %>"<%= ' checked="checked"' if @duplicate.age_groups.include?(id) %> />
					<%= group %>
				</label>
			</div>
			<% end %>
		</div>
	</div>
	<% @duplicate.visits.each_with_index do |visit, i| %>
	<hr />
	<h4><%= (@duplicate.visits.size - i).ordinalize %> Visit</h4>
	<dl>
		<dt>Team Members:</dt>
		<dd><%= visit.team %></dd>

		<dt>Date:</dt>
		<dd><%= visit.date %></dd>

		<dt>Outcome:</dt>
		<dd><%= visit.outcome_text %></dd>

		<dt>Conversation Themes Covered:</dt>
		<dd><%= visit.themes.empty? ? "-" : visit.themes.map {|a| Visit::THEMES[a]}.join(", ") %></dd>

		<dt>Notes:</dt>
		<dd><%=simple_format visit.notes.blank? ? "-" : visit.notes %></dd>
	</dl>
	<% end %>
	<div class="form-group">
		<button class="btn btn-primary right" type="submit">Merge</button>
	</div>
<% end %>