config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :campaigns, only: [:index, :create, :new, :show, :destroy] do
    resource :search, only: [:new, :show]
    resources :permissions, only: [:create]
    resources :entries, only: [:index] do
      post 'submit', on: :collection
    end
    resources :duplicates, only: [:index, :show] do
      post 'merge', on: :member
      post 'reject', on: :member
    end
    get 'export', on: :member
  end
  resources :entries, only: [:show, :update, :edit]
  resources :visits, only: [:edit, :update]

  root to: "home#show"

  get 'hello_world', to: 'hello_world#index'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	SEARCH_FIELDS = ["entries.street", "entries.people", "entries.contact", "visits.notes", "visits.team"]

	def new
		@campaign = Campaign.find(params[:campaign_id])
		unless current_user.can_see?(@campaign)
			redirect_to '/'
			return
		end
	end

	def show
		@campaign = Campaign.find(params[:campaign_id])
		unless current_user.can_see?(@campaign)
			redirect_to '/'
			return
		end
		@entries = @campaign.entries.joins(:visits).order(last_visit: :desc, street: :desc, street_number: :desc, unit_number: :desc)
		if params[:keywords].present?
			keywords = params[:keywords].split(" ")
			keyword_params = {}
			pnum = 0
			keyword_query = keywords.map do |k|
				pname = "param#{pnum}"
				keyword_params[pname.to_sym] = "%#{k}%"
				"(" + SEARCH_FIELDS.map do |f|
					"#{f} ILIKE :#{pname}"
				end.join(" OR ") + ")"
			end.join(" AND ")
			@entries = @entries.where(keyword_query, keyword_params)
		end
		@entries = @entries.where("entries.age_groups @> ARRAY[?]", params[:age_group]) unless params[:age_group].blank?
		if params[:outcomes].present?
			@entries = @entries.where("entries.last_outcome IN (?)", params[:outcomes])
		end
		@entries = @entries.to_a.uniq
	end
end

app/views/searches/new.html.erb
<h3 class="card-title">Search: <%= @campaign.name %></h3>
<%= form_tag(campaign_search_path(@campaign), method: :get) do %>
	<div class="form-group">
		<label for="keywords">Keywords:</label>
		<input class="form-control" type="text" name="keywords" id="keywords" />
	</div>
	<div class="form-group">
		<label for="age-group">Age Group:</label>
		<select class="form-control" name="age_group" id="age-group">
		<option value="">Any</option>
		<% Entry::AGE_GROUPS.each do |id, group| %>
			<option value="<%= id %>"><%= group %></option>
		<% end %>
		</select>
	</div>
	<div class="form-group">
		Outcome:
		<% Visit::OUTCOMES.each do |id, outcome| %>
		<div class="form-check">
			<label class="form-check-label">
				<input type="checkbox" class="form-check-input themes" name="outcomes[]" value="<%= id %>" id="outcomes-<%= id %>" />
				<%= outcome %>
			</label>
		</div>
		<% end %>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Search</button>
	</div>
<% end %>

app/views/searches/show.html.erb
<h3 class="card-title"><%= link_to "< #{@campaign.name}", campaign_path(@campaign) %> Search</h3>
<div class="card-block">
	<%= link_to "Search", new_campaign_search_path(@campaign.id), class: "btn btn-primary" %>
</div>
<%= render "campaigns/entry_list", entries: @entries %>