config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :campaigns, only: [:index, :create, :new, :show, :destroy] do
    resource :search, only: [:new, :show]
    resources :permissions, only: [:create]
    resources :entries, only: [:index] do
      post 'submit', on: :collection
    end
    resources :duplicates, only: [:index, :show] do
      post 'merge', on: :member
      post 'reject', on: :member
    end
    get 'export', on: :member
  end
  resources :entries, only: [:show, :update, :edit]
  resources :visits, only: [:edit, :update]

  root to: "home#show"

  get 'hello_world', to: 'hello_world#index'
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	before_create { self.id = SecureRandom.base58(24) }

	has_many :permissions, dependent: :destroy
	has_many :entries, dependent: :destroy
	has_many :duplicates, dependent: :destroy

	def check_duplicates
		return unless unchecked_duplicates?
		potentials = entries.select(:street_number, :unit_number)
			.group(:street_number, :unit_number)
			.having("COUNT(*)>1 AND (? IS NULL OR MAX(updated_at)>?)", last_duplicate_check, last_duplicate_check)
		potentials.each do |potential|
			Duplicate.create_for_entries(id, potential)
		end
	end

	def unchecked_duplicates?
		entries.exists? && (last_duplicate_check.nil? || entries.maximum(:updated_at) > last_duplicate_check)
	end
end

app/controllers/campaigns_controller.rb
require 'csv'

class CampaignsController < ApplicationController
	before_action :require_login

	def new
	end

	def index
		@user_campaigns = current_user.campaigns.order(created_at: :desc).to_a
	end

	def create
		Campaign.transaction do
			campaign = Campaign.create!(name: params[:name])
			campaign.permissions.create!(email: current_user.email, level: "owner")
		end
		redirect_to action: :index
	end

	def show
		@campaign = Campaign.find(params[:id])
		unless current_user.can_see?(@campaign)
			redirect_to '/'
			return
		end
		@entries = @campaign.entries.order(last_visit: :desc, street: :desc, street_number: :desc, unit_number: :desc).to_a
		@role = @campaign.permissions.where(email: current_user.email).take.level
		@campaign.check_duplicates
		@duplicate_count = @campaign.duplicates.where(status: "potential").count
	end

	def export
		@campaign = Campaign.find(params[:id])
		unless current_user.can_see?(@campaign)
			redirect_to '/'
			return
		end
		@entries = @campaign.entries.order(created_at: :desc).to_a

		csv_data = CSV.generate do |csv|
		  csv << ["Date", "Team", "Street", "Street Number", "Unit", "Outcome", "People", "Contact", "Age Groups", "Themes", "Notes"]
		  @entries.each do |entry|
				csv << [
					entry.last_visit,
					entry.all_teams,
					entry.street,
					entry.street_number,
					entry.unit_number,
					entry.last_outcome_text,
					entry.people,
					entry.contact,
					entry.age_groups.map{|a| Entry::AGE_GROUPS[a]}.join(", "),
					entry.all_themes.map{|t| Visit::THEMES[t]}.join(", "),
					entry.all_notes
				]
			end
		end

		filename = @campaign.name.gsub(/[^ A-Za-z0-9]/, "").gsub(" ","-").downcase+".csv"
		send_data(csv_data,
		  :filename => filename,
		  :type => "text/csv")
	end

	def destroy
	end
end

app/views/campaigns/_entry_list.html.erb
<div class="card-block">
	<table class="table" id="entry-links">
		<thead>
			<tr>
				<th>Address</th>
				<th>Outcome</th>
				<th>People</th>
				<th>Date</th>
			</tr>
		</thead>
		<tbody>
			<% entries.each do |entry| %>
			<tr data-href="<%= entry_path(entry.id) %>">
				<td><%= entry.full_address %></td>
				<td><%= entry.last_outcome_text %></td>
				<td><%= entry.people %></td>
				<td><%= entry.last_visit %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/campaigns/index.html.erb
<h3 class="card-title">My Campaigns</h3>
<div>
	<%= link_to "Create Campaign", new_campaign_path, class: "btn btn-primary btn-sm" %>
</div>
<hr />
<% if @user_campaigns.size > 0 %>
<% @user_campaigns.each do |campaign| %>
	<a class="btn btn-secondary btn-block" href="<%= campaign_path(campaign) %>"><%= campaign.name %></a>
<% end %>
<% else %>
<div class="card-block">
	<p class="card-text">You do not currently have any campaigns.</p>
</div>
<% end %>

app/views/campaigns/new.html.erb
<h3 class="card-title">Create Campaign</h3>
<%= form_tag(campaigns_path) do %>
	<div class="form-group">
		<label for="name">Campaign Name (Location, Time)</label>
		<input type="text" name="name" id="name" placeholder="Name" class="form-control col-sm-4" />
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Create</button>
	</div>
<% end %>

app/views/campaigns/show.html.erb
<h3 class="card-title"><%= @campaign.name %></h3>
<%= link_to "Export Spreadsheet", export_campaign_path(@campaign.id), target: "_blank", class: "btn btn-primary" %>
<% if @role == "owner" %>
<div class="card-block row">
	<div class="col col-auto"><strong>Users</strong>:</div>
	<div class="col">
		<p class="card-text"><%= @campaign.permissions.map(&:email).join(", ") %></p>
		<%= form_tag(campaign_permissions_path(@campaign.id), class: "form-inline") do %>
			<input type="text" name="email" id="email" placeholder="Email" class="form-control form-control-sm" />
			&nbsp;
			<button type="submit" class="btn btn-primary btn-sm">Add User</button>
		<% end %>
	</div>
</div>
<% end %>
<% if @duplicate_count > 0 %>
<div class="card-block">
	<%= link_to pluralize(@duplicate_count, "Potential Duplicate") + " (view)", campaign_duplicates_path(@campaign.id) %>
</div>
<% end %>
<div class="card-block">
	<strong>Data Entry Form:</strong> <%= link_to campaign_entries_url(@campaign.id), campaign_entries_path(@campaign.id) %>
</div>
<div class="card-block">
	<%= link_to "Search", new_campaign_search_path(@campaign.id), class: "btn btn-primary" %>
</div>
<%= render "entry_list", entries: @entries %>